### ISSUE TITLE
Params in URL

### ISSUE THREAD

**Issue by Saikurin** [Reeko94/scolabs-3IW#42]
Avoir la possibilité d'avoir une url comme suit :
- /classrooms/3IW1/edit

et dans le fichier YAML avoir :
```YAML
/classrooms/{name}/edit:
  controller: Classrooms
  action: edit
  params: name
```
